### ISSUE TITLE
Feature: Register thesis project

### ISSUE THREAD

**Issue by rogargon** [UdL-EPS-SoftArch/entsoftarch-1516-server#20]

**Comment by tativilalta** [comment]
in order to accept thesis projects
as a coordinator
I want to accept proposals with its participants

**Comment by rogargon** [comment]
Please, try to generate the ProposalRegistrationRepository and do a pull request to integrate this class into master

**Comment by rogargon** [comment]
Please, rebase your branch and perform a pull request to get your contributions into master. Otherwise, you do not have any commit for the qualifications for the first iteration!
